#!/usr/bin/env bash
# tests/snapshot.test.sh
#
# Offline exercise of scripts/build_snapshot.py against the small fixtures in tests/fixtures/.
# Touches no network. Prints "ok"/"FAIL" per check and exits non-zero if anything failed.
#
#   bash tests/snapshot.test.sh
#
# Requires: python3 (3.9+), node (only for the two "output is valid JS" checks -- if node is not
# on PATH those two checks are skipped with a note, everything else still runs).
set -u

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

PY=python3
POTA_CSV="tests/fixtures/sample_all_parks_ext.csv"
SOTA_CSV="tests/fixtures/sample_summitslist.csv"
TODAY="2026-08-31"   # pin "today" so retired-summit filtering is deterministic regardless of run date
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

FAILURES=0
CHECKS=0
pass() { CHECKS=$((CHECKS + 1)); printf '  ok   - %s\n' "$1"; }
fail() { CHECKS=$((CHECKS + 1)); FAILURES=$((FAILURES + 1)); printf '  FAIL - %s\n' "$1"; }
note() { printf '  --   - %s (skipped)\n' "$1"; }

# Run a python3 helper script (heredoc'd to $WORK below); dynamic values are passed as argv, not
# string-interpolated into the script, so the checks below are safe to write as plain Python.
check_py() {
  local desc="$1" script="$2"; shift 2
  local out
  if out=$("$PY" "$script" "$@" 2>&1); then
    pass "$desc"
  else
    fail "$desc"
    printf '%s\n' "$out" | sed 's/^/         /'
  fi
}

# Run a shell command, expecting exit code 0.
check_ok() {
  local desc="$1"; shift
  local out
  if out=$("$@" 2>&1); then
    pass "$desc"
  else
    fail "$desc"
    printf '%s\n' "$out" | sed 's/^/         /'
  fi
}

# Run a shell command, expecting a non-zero exit code, and (optionally, if $2 is non-empty)
# grep its combined output for a required substring. Always call with an explicit $2 (pass ""
# to skip the substring check) -- every argument after that is the command to run.
check_fails() {
  local desc="$1" needle="$2"; shift 2
  local out rc
  out=$("$@" 2>&1); rc=$?
  if [ "$rc" -eq 0 ]; then
    fail "$desc (expected non-zero exit, got 0)"
    return
  fi
  if [ -n "$needle" ] && ! printf '%s' "$out" | grep -qF -e "$needle"; then
    fail "$desc (exit $rc, but message did not mention '$needle')"
    printf '%s\n' "$out" | sed 's/^/         /'
    return
  fi
  pass "$desc"
}

echo "== scripts/build_snapshot.py offline test suite =="
echo "root: $ROOT"
echo

# --------------------------------------------------------------------------- #
# 0. sanity
# --------------------------------------------------------------------------- #
check_ok "--help exits 0" "$PY" scripts/build_snapshot.py --help
[ -f "$POTA_CSV" ] || fail "fixture exists: $POTA_CSV"
[ -f "$SOTA_CSV" ] || fail "fixture exists: $SOTA_CSV"
echo

# --------------------------------------------------------------------------- #
# 1. default run: --programs US (default), --sota-assoc-prefix W (default)
# --------------------------------------------------------------------------- #
echo "-- default run (US parks, W summits) --"
DEFAULT_OUT="$WORK/snapshot_default.js"
DEFAULT_ERR="$WORK/default.stderr"
check_ok "default run exits 0" \
  "$PY" scripts/build_snapshot.py --pota-csv "$POTA_CSV" --sota-csv "$SOTA_CSV" \
    --out "$DEFAULT_OUT" --today "$TODAY" --user-agent "pota-sota-map snapshot builder (tests)"
"$PY" scripts/build_snapshot.py --pota-csv "$POTA_CSV" --sota-csv "$SOTA_CSV" \
  --out "$DEFAULT_OUT" --today "$TODAY" >"$DEFAULT_ERR" 2>&1

if command -v node >/dev/null 2>&1; then
  cat > "$WORK/check_default.js" <<'JSEOF'
const fs = require('fs');
const path = process.argv[2];
const s = fs.readFileSync(path, 'utf8');
const w = {};
new Function('window', s)(w);
const snap = w.PSM_SNAPSHOT;
if (!snap) throw new Error('window.PSM_SNAPSHOT was not set');
const p = snap.pota.rows.length, n = snap.sota.rows.length;
if (p !== 22) throw new Error('expected 22 pota rows, got ' + p);
if (n !== 16) throw new Error('expected 16 sota rows, got ' + n);
console.log(p, n);
JSEOF
  check_ok "output is valid JS; window.PSM_SNAPSHOT has 22 pota rows, 16 sota rows" \
    node "$WORK/check_default.js" "$DEFAULT_OUT"
else
  note "output is valid JS (node not on PATH)"
fi

cat > "$WORK/check_default.py" <<'PYEOF'
import json, re, sys

path = sys.argv[1]
text = open(path, encoding='utf-8').read()
lines = text.split('\n', 1)
first_line = lines[0]

m = re.match(
    r'^// Generated by scripts/build_snapshot\.py on (\S+) — (\d+) parks, (\d+) summits$',
    first_line)
assert m, 'header comment line missing/malformed: ' + repr(first_line)
assert (m.group(2), m.group(3)) == ('22', '16'), 'header comment counts wrong: ' + first_line

body = lines[1]
assert body.startswith('window.PSM_SNAPSHOT = '), 'missing window.PSM_SNAPSHOT = wrapper'
assert body.rstrip('\n').endswith(';'), 'missing trailing semicolon'
payload = body[len('window.PSM_SNAPSHOT = '):].rstrip('\n')
assert payload.endswith(';')
payload = payload[:-1]

obj = json.loads(payload)

# compact (separators (',', ':')) and ensure_ascii=False: re-serializing the parsed object the
# same way must reproduce the payload byte-for-byte. (A naive "', ' not in payload" substring
# check is NOT safe here -- e.g. the park name "Cape Hatteras National Seashore, Outer Banks"
# legitimately contains ", " as data.)
assert json.dumps(obj, separators=(',', ':'), ensure_ascii=False) == payload, \
    'payload is not exactly json.dumps(obj, separators=(",",":"), ensure_ascii=False)'
assert obj['pota']['columns'] == ["ref", "name", "lat", "lon", "grid", "loc", "active"]
assert obj['sota']['columns'] == ["code", "name", "lat", "lon", "altM", "altFt", "points", "bonus",
                                   "validFrom", "validTo", "actCount", "actDate", "actCall",
                                   "assocName", "regionName"]

pota_rows = obj['pota']['rows']
sota_rows = obj['sota']['rows']
pota_by_ref = {r[0]: r for r in pota_rows}
sota_by_code = {r[0]: r for r in sota_rows}

# only US parks / W associations by default
assert all(r[0].split('-', 1)[0] == 'US' for r in pota_rows), 'non-US park present by default'
assert all(r[0].split('/', 1)[0].startswith('W') for r in sota_rows), 'non-W summit present by default'
assert 'VE-0001' not in pota_by_ref and 'GB-0001' not in pota_by_ref, 'VE/GB leaked into default (US-only) output'
assert 'VE2/QC-001' not in sota_by_code and 'GM/SS-001' not in sota_by_code, 'VE2/GM leaked into default (W-only) output'

# retired summit (ValidTo=31/12/2015) excluded by default
assert 'W1/HA-099' not in sota_by_code, 'retired summit not excluded by default'

# inactive parks (active=0) excluded by default
assert 'US-0018' not in pota_by_ref, 'inactive park US-0018 not excluded by default'
assert 'US-0019' not in pota_by_ref, 'inactive park US-0019 not excluded by default'

# malformed lat/lon row skipped
assert 'US-0021' not in pota_by_ref, 'malformed lat/lon row (US-0021) was not skipped'

# duplicate reference/code resolved to the FIRST occurrence, not the later duplicate
assert sum(1 for r in pota_rows if r[0] == 'US-0001') == 1, 'duplicate US-0001 not deduped'
assert pota_by_ref['US-0001'][1] == 'Acadia National Park', 'dedupe kept the later duplicate, not the first'
assert sum(1 for r in sota_rows if r[0] == 'W2/GC-001') == 1, 'duplicate W2/GC-001 not deduped'
assert sota_by_code['W2/GC-001'][1] == 'Slide Mountain', 'dedupe kept the later duplicate, not the first'

# the exact worked example from ARCHITECTURE.md's snapshot.js contract, verbatim
assert pota_by_ref['US-0001'] == ["US-0001", "Acadia National Park", 44.31, -68.2034, "FN54vh", "US-ME", 1], \
    'US-0001 row does not match the documented contract example: ' + repr(pota_by_ref['US-0001'])

# lat/lon rounded to 5 decimals (values already <=5dp in the fixture; a spot check is enough here,
# --bbox section below round-trips a >5dp input)
assert pota_by_ref['US-0008'][2] == 44.428 and pota_by_ref['US-0008'][3] == -110.5885

# dates are ISO YYYY-MM-DD, never DD/MM/YYYY, on every kept summit
iso_date = re.compile(r'^\d{4}-\d{2}-\d{2}$')
for r in sota_rows:
    assert iso_date.match(r[8]), 'validFrom not ISO: ' + repr(r)
    assert iso_date.match(r[9]), 'validTo not ISO: ' + repr(r)
    if r[11] is not None:
        assert iso_date.match(r[11]), 'actDate not ISO: ' + repr(r)
assert sota_by_code['W2/GC-001'][8] == '2010-05-01' and sota_by_code['W2/GC-001'][9] == '2099-12-31'

# null-if-blank: actCount "0" in the CSV -> integer 0 (not null); actDate/actCall genuinely
# blank -> null; a summit with actCount itself blank in the CSV -> actCount null too
never_activated = sota_by_code['W1/HA-002']
assert never_activated[10] == 0 and never_activated[11] is None and never_activated[12] is None
assert sota_by_code['W6/SD-001'][10] is None, 'blank ActivationCount should become null, not 0'

# integers stay integers (not "8" or 8.0), floats stay floats
assert isinstance(sota_by_code['W1/HA-001'][4], int)   # altM
assert isinstance(sota_by_code['W1/HA-001'][6], int)   # points
assert isinstance(pota_by_ref['US-0001'][2], float)    # lat

# rows sorted by ref/code
assert [r[0] for r in pota_rows] == sorted(r[0] for r in pota_rows), 'pota rows not sorted by ref'
assert [r[0] for r in sota_rows] == sorted(r[0] for r in sota_rows), 'sota rows not sorted by code'

# CSV quoting round-tripped correctly (comma-in-name, doubled-double-quote-in-name), trimmed
assert pota_by_ref['US-0016'][1] == 'Joe "Trapper" Smith Memorial Park'
assert pota_by_ref['US-0017'][1] == 'Cape Hatteras National Seashore, Outer Banks'

# grid/loc are null (not "") when the source field is blank -- GB rows have blank locationDesc,
# but GB is filtered out by default; check via the multi-program payload written by check 2 instead.

print('OK')
PYEOF
check_py "default output: structure, filters, dedupe, dates, contract-example row" "$WORK/check_default.py" "$DEFAULT_OUT"

check_ok "stderr summary mentions POTA/SOTA counts and the output path" \
  bash -c "grep -q 'POTA:' '$DEFAULT_ERR' && grep -q 'SOTA:' '$DEFAULT_ERR' && grep -q 'wrote' '$DEFAULT_ERR'"
echo

# --------------------------------------------------------------------------- #
# 2. multi-program run: --programs US VE --sota-assoc-prefix W VE
# --------------------------------------------------------------------------- #
echo "-- multi-program run (--programs US VE --sota-assoc-prefix W VE) --"
MULTI_OUT="$WORK/snapshot_multi.js"
check_ok "multi-program run exits 0" \
  "$PY" scripts/build_snapshot.py --programs US VE --sota-assoc-prefix W VE \
    --pota-csv "$POTA_CSV" --sota-csv "$SOTA_CSV" --out "$MULTI_OUT" --today "$TODAY"

cat > "$WORK/check_multi.py" <<'PYEOF'
import json, sys

path = sys.argv[1]
text = open(path, encoding='utf-8').read()
payload = text.split('\n', 1)[1].strip()
assert payload.startswith('window.PSM_SNAPSHOT = ') and payload.endswith(';')
obj = json.loads(payload[len('window.PSM_SNAPSHOT = '):-1])

pota_by_ref = {r[0]: r for r in obj['pota']['rows']}
sota_by_code = {r[0]: r for r in obj['sota']['rows']}

# Canadian rows now included ...
assert 'VE-0001' in pota_by_ref, '--programs US VE should include VE-0001'
assert 'VE-0002' in pota_by_ref and 'VE-0003' in pota_by_ref
assert 'VE2/QC-001' in sota_by_code, '--sota-assoc-prefix W VE should include VE2/QC-001'

# ... UTF-8/diacritic preserved end to end (name has an "e with acute accent"), not escaped
assert sota_by_code['VE2/QC-001'][1] == 'Mont Bélair'
assert '\\u00e9' not in text and '\\u00E9' not in text, \
    'ensure_ascii must be False: diacritics should be literal UTF-8, not \\uXXXX-escaped'

# ... but GB (not in --programs) and GM (does not start with W or VE) still excluded
assert 'GB-0001' not in pota_by_ref, 'GB should stay excluded (not in --programs US VE)'
assert 'GM/SS-001' not in sota_by_code, 'GM should stay excluded (matches neither W nor VE prefix)'

# grid/loc null (not "") for a row whose source locationDesc was blank (the GB rows have blank
# locationDesc in the fixture, but GB is excluded here too -- so check active-but-blank-grid via
# the "loc" contract type instead: every kept row's loc, when present, is a non-empty string)
for r in obj['pota']['rows']:
    assert r[5] is None or (isinstance(r[5], str) and r[5] != ''), 'loc should be null or a non-empty string, never ""'
    assert r[4] is None or (isinstance(r[4], str) and r[4] != ''), 'grid should be null or a non-empty string, never ""'

print('OK')
PYEOF
check_py "multi-program output: VE included, diacritic preserved, GB/GM still excluded" "$WORK/check_multi.py" "$MULTI_OUT"
echo

# --------------------------------------------------------------------------- #
# 3. --include-inactive-parks / --include-retired
# --------------------------------------------------------------------------- #
echo "-- --include-inactive-parks / --include-retired --"
ALL_OUT="$WORK/snapshot_all.js"
check_ok "include-inactive/include-retired run exits 0" \
  "$PY" scripts/build_snapshot.py --include-inactive-parks --include-retired \
    --pota-csv "$POTA_CSV" --sota-csv "$SOTA_CSV" --out "$ALL_OUT" --today "$TODAY"

cat > "$WORK/check_all.py" <<'PYEOF'
import json, sys

path = sys.argv[1]
text = open(path, encoding='utf-8').read()
payload = text.split('\n', 1)[1].strip()
obj = json.loads(payload[len('window.PSM_SNAPSHOT = '):-1])
pota_by_ref = {r[0]: r for r in obj['pota']['rows']}
sota_by_code = {r[0]: r for r in obj['sota']['rows']}

assert 'US-0018' in pota_by_ref and pota_by_ref['US-0018'][6] == 0, '--include-inactive-parks should keep US-0018 with active=0'
assert 'US-0019' in pota_by_ref and pota_by_ref['US-0019'][6] == 0

assert 'W1/HA-099' in sota_by_code, '--include-retired should keep W1/HA-099'
retired = sota_by_code['W1/HA-099']
assert retired[8] == '2004-01-01' and retired[9] == '2015-12-31'

# still no VE/GB/GM leaking in from these two flags alone (they're orthogonal to --programs)
assert 'VE-0001' not in pota_by_ref and 'GM/SS-001' not in sota_by_code

# still no malformed/duplicate rows
assert 'US-0021' not in pota_by_ref
assert sum(1 for r in obj['pota']['rows'] if r[0] == 'US-0001') == 1

print('OK')
PYEOF
check_py "include-inactive/include-retired output: previously-excluded rows now present" "$WORK/check_all.py" "$ALL_OUT"
echo

# --------------------------------------------------------------------------- #
# 4. --bbox (applied to both datasets)
# --------------------------------------------------------------------------- #
echo "-- --bbox --"
BBOX_OUT="$WORK/snapshot_bbox.js"
# Roughly the northeastern US: should keep US-0003 (NH), US-0004 (VT) and the W1/W2/W3 summits,
# but exclude everything west-coast/Idaho/Arizona/etc. and US-0001 Acadia (ME, east of -70).
check_ok "bbox run exits 0" \
  "$PY" scripts/build_snapshot.py --bbox 40.0 -80.0 45.0 -70.0 \
    --pota-csv "$POTA_CSV" --sota-csv "$SOTA_CSV" --out "$BBOX_OUT" --today "$TODAY"

cat > "$WORK/check_bbox.py" <<'PYEOF'
import json, sys

path = sys.argv[1]
text = open(path, encoding='utf-8').read()
payload = text.split('\n', 1)[1].strip()
obj = json.loads(payload[len('window.PSM_SNAPSHOT = '):-1])
pota_refs = {r[0] for r in obj['pota']['rows']}
sota_codes = {r[0] for r in obj['sota']['rows']}

assert pota_refs == {'US-0003', 'US-0004'}, 'unexpected pota refs in bbox: ' + repr(sorted(pota_refs))
assert 'US-0001' not in pota_refs, 'Acadia (ME) is east of the box and must be excluded'
assert 'US-0009' not in pota_refs, 'Yosemite (CA) is far outside the box'

expected_sota = {'W1/CN-001', 'W1/HA-001', 'W1/HA-002', 'W1/HA-003', 'W2/GC-001', 'W2/NJ-001', 'W3/SH-001'}
assert sota_codes == expected_sota, 'unexpected sota codes in bbox: ' + repr(sorted(sota_codes))

for r in obj['pota']['rows']:
    assert 40.0 <= r[2] <= 45.0 and -80.0 <= r[3] <= -70.0
for r in obj['sota']['rows']:
    assert 40.0 <= r[2] <= 45.0 and -80.0 <= r[3] <= -70.0

print('OK')
PYEOF
check_py "bbox output: both datasets restricted to the box" "$WORK/check_bbox.py" "$BBOX_OUT"
echo

# --------------------------------------------------------------------------- #
# 5. --format json
# --------------------------------------------------------------------------- #
echo "-- --format json --"
JSON_OUT="$WORK/snapshot.json"
check_ok "--format json run exits 0" \
  "$PY" scripts/build_snapshot.py --pota-csv "$POTA_CSV" --sota-csv "$SOTA_CSV" \
    --out "$JSON_OUT" --format json --today "$TODAY"

cat > "$WORK/check_json.py" <<'PYEOF'
import json, sys

path = sys.argv[1]
text = open(path, encoding='utf-8').read()
assert not text.lstrip().startswith('//'), '--format json must not include the // header comment'
assert 'window.PSM_SNAPSHOT' not in text, '--format json must not include the window.PSM_SNAPSHOT wrapper'
obj = json.loads(text)  # must parse as a bare, complete JSON document
assert len(obj['pota']['rows']) == 22 and len(obj['sota']['rows']) == 16

# still compact + ensure_ascii=False (see the equivalent, more detailed comment in check_default.py)
assert json.dumps(obj, separators=(',', ':'), ensure_ascii=False) == text.rstrip('\n'), \
    '--format json output is not exactly json.dumps(obj, separators=(",",":"), ensure_ascii=False)'
print('OK')
PYEOF
check_py "--format json output: bare JSON, no wrapper/comment, parses standalone" "$WORK/check_json.py" "$JSON_OUT"
echo

# --------------------------------------------------------------------------- #
# 6. --offline / --cache-dir round trip
# --------------------------------------------------------------------------- #
echo "-- --offline / cache round-trip --"
CACHE_DIR="$WORK/cache"
mkdir -p "$CACHE_DIR"
cp "$POTA_CSV" "$CACHE_DIR/all_parks_ext.csv"
cp "$SOTA_CSV" "$CACHE_DIR/summitslist.csv"
OFFLINE_OUT="$WORK/snapshot_offline.js"
check_ok "--offline with a populated cache exits 0" \
  "$PY" scripts/build_snapshot.py --offline --cache-dir "$CACHE_DIR" --out "$OFFLINE_OUT" --today "$TODAY"

if [ -f "$OFFLINE_OUT" ] && [ -f "$DEFAULT_OUT" ]; then
  # identical byte-for-byte except the "generated" timestamp
  A=$(sed -E 's/[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}Z/TS/g' "$OFFLINE_OUT")
  B=$(sed -E 's/[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}Z/TS/g' "$DEFAULT_OUT")
  if [ "$A" = "$B" ]; then
    pass "--offline (via cache) output matches --pota-csv/--sota-csv output (modulo timestamp)"
  else
    fail "--offline (via cache) output matches --pota-csv/--sota-csv output (modulo timestamp)"
  fi
else
  fail "--offline (via cache) output matches --pota-csv/--sota-csv output (modulo timestamp)"
fi

EMPTY_CACHE="$WORK/empty-cache"
mkdir -p "$EMPTY_CACHE"
check_fails "--offline with an empty cache exits non-zero and mentions --offline/--pota-csv" \
  "--pota-csv" "$PY" scripts/build_snapshot.py --offline --cache-dir "$EMPTY_CACHE" --out "$WORK/x.js"
echo

# --------------------------------------------------------------------------- #
# 7. error handling: bad local paths / malformed CSV
# --------------------------------------------------------------------------- #
echo "-- error handling --"
check_fails "nonexistent --pota-csv path exits non-zero" \
  "" "$PY" scripts/build_snapshot.py --pota-csv "$WORK/does-not-exist.csv" --sota-csv "$SOTA_CSV" --out "$WORK/x.js"

printf 'reference,name\nUS-0001,Test\n' > "$WORK/bad_pota.csv"
check_fails "POTA CSV missing required columns exits non-zero" \
  "missing expected column" "$PY" scripts/build_snapshot.py --pota-csv "$WORK/bad_pota.csv" --sota-csv "$SOTA_CSV" --out "$WORK/x.js"

printf 'not,a,sota,header\n1,2,3,4\n' > "$WORK/bad_sota.csv"
check_fails "SOTA CSV missing required columns exits non-zero" \
  "missing expected column" "$PY" scripts/build_snapshot.py --pota-csv "$POTA_CSV" --sota-csv "$WORK/bad_sota.csv" --out "$WORK/x.js"
echo

# --------------------------------------------------------------------------- #
# 8. tests/fixtures/snapshot_sample.js (the realistic NY/W2-GC-backed fixture for e2e/browser
#    tests; see tests/fixtures/make_snapshot_sample.py) is present and well-formed
# --------------------------------------------------------------------------- #
echo "-- tests/fixtures/snapshot_sample.js --"
SAMPLE="tests/fixtures/snapshot_sample.js"
if [ -f "$SAMPLE" ]; then
  pass "$SAMPLE exists"
  if command -v node >/dev/null 2>&1; then
    cat > "$WORK/check_sample.js" <<'JSEOF'
const fs = require('fs');
const s = fs.readFileSync(process.argv[2], 'utf8');
const w = {};
new Function('window', s)(w);
const snap = w.PSM_SNAPSHOT;
if (!snap) throw new Error('window.PSM_SNAPSHOT was not set');
if (snap.pota.rows.length < 800) throw new Error('expected >=800 pota rows, got ' + snap.pota.rows.length);
if (snap.sota.rows.length < 100) throw new Error('expected >=100 sota rows, got ' + snap.sota.rows.length);
const harriman = snap.pota.rows.find(r => r[0] === 'US-2069');
if (!harriman || harriman[1] !== 'Harriman State Park') throw new Error('US-2069 Harriman State Park missing/wrong');
const slide = snap.sota.rows.find(r => r[0] === 'W2/GC-001');
if (!slide || slide[1] !== 'Slide Mountain') throw new Error('W2/GC-001 Slide Mountain missing/wrong');
console.log(snap.pota.rows.length, snap.sota.rows.length);
JSEOF
    check_ok "$SAMPLE is valid JS and contains the real Harriman/Slide Mountain rows" \
      node "$WORK/check_sample.js" "$SAMPLE"
  else
    note "$SAMPLE is valid JS (node not on PATH)"
  fi

  cat > "$WORK/check_sample.py" <<'PYEOF'
import json, re, sys

path = sys.argv[1]
text = open(path, encoding='utf-8').read()
assert text.startswith('// Generated by scripts/build_snapshot.py on ')
payload = text.split('\n', 1)[1].strip()
assert payload.startswith('window.PSM_SNAPSHOT = ') and payload.endswith(';')
obj = json.loads(payload[len('window.PSM_SNAPSHOT = '):-1])

assert len(obj['pota']['rows']) >= 800
assert len(obj['sota']['rows']) >= 100
pota_by_ref = {r[0]: r for r in obj['pota']['rows']}
sota_by_code = {r[0]: r for r in obj['sota']['rows']}

harriman = pota_by_ref.get('US-2069')
assert harriman is not None, 'US-2069 (Harriman State Park, real NY fixture) missing from snapshot_sample.js'
assert harriman[1] == 'Harriman State Park' and harriman[5] == 'US-NY'

slide = sota_by_code.get('W2/GC-001')
assert slide is not None, 'W2/GC-001 (Slide Mountain, real W2/GC fixture) missing from snapshot_sample.js'
assert slide[1] == 'Slide Mountain' and slide[13] == 'USA - NJ / NY' and slide[14] == 'Greater Catskills'

# the long-tail sample CSV rows are merged in too (not just the two big real fixtures)
assert 'US-0001' in pota_by_ref and pota_by_ref['US-0001'][1] == 'Acadia National Park'

# no leftover artefacts from the small CSV's deliberately-malformed/duplicate rows
assert 'US-0021' not in pota_by_ref
assert sum(1 for r in obj['pota']['rows'] if r[0] == 'US-0001') == 1
assert sum(1 for r in obj['sota']['rows'] if r[0] == 'W2/GC-001') == 1

# sorted
assert [r[0] for r in obj['pota']['rows']] == sorted(r[0] for r in obj['pota']['rows'])
assert [r[0] for r in obj['sota']['rows']] == sorted(r[0] for r in obj['sota']['rows'])

print('OK')
PYEOF
  check_py "$SAMPLE structure: real Harriman + Slide Mountain rows, long tail merged, sorted, deduped" \
    "$WORK/check_sample.py" "$SAMPLE"
else
  fail "$SAMPLE exists (run: python3 tests/fixtures/make_snapshot_sample.py)"
fi
echo

# --------------------------------------------------------------------------- #
echo "== $((CHECKS - FAILURES))/$CHECKS checks passed =="
if [ "$FAILURES" -gt 0 ]; then
  echo "$FAILURES check(s) FAILED"
  exit 1
fi
exit 0
